// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD786kha1df6raFC_oo2GKP-DFFHBHqBjI',
    appId: '1:877341211246:web:0a2641b2dcd6c0ff0a047f',
    messagingSenderId: '877341211246',
    projectId: 'jizanquiz',
    authDomain: 'jizanquiz.firebaseapp.com',
    storageBucket: 'jizanquiz.appspot.com',
    measurementId: 'G-GCB6352QZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG36D7zl2zOywj5qcRPLjQsg3tNkUFBm0',
    appId: '1:877341211246:android:8b0b190cb00965e70a047f',
    messagingSenderId: '877341211246',
    projectId: 'jizanquiz',
    storageBucket: 'jizanquiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQf0Mkm5aX7wsoDL7VTA9c6VRwziwVZho',
    appId: '1:877341211246:ios:27fa0b5fe6367a6d0a047f',
    messagingSenderId: '877341211246',
    projectId: 'jizanquiz',
    storageBucket: 'jizanquiz.appspot.com',
    iosClientId: '877341211246-ffokhnqbosur6hcegm1voc8j71t1uik0.apps.googleusercontent.com',
    iosBundleId: 'com.jizan.quiz.jizanUniversityQuiz',
  );
}
